[package]
name = "libelf_parse"
edition = "2021"

[lib]
name = "elf_parse"
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
opt-level = 3
strip = true
codegen-units = 1

[dependencies.elf]
version = "0.7.4"
default-features = false
